src/bin/common/library.cpp
src/bin/common/library.h
src/bin/migrate/softhsm2-migrate.cpp
src/bin/util/softhsm2-util.cpp

This makes command line utilities much more useful when debugging library related problems. dlopen() version works fine on Fedora 21, LoadLibrary version is untested.

Return detailed error message to loadLibrary().

---

src/bin/dump/Makefile.am

Only install softhsm2-dump-db manpage if executable is installed

Only install softhsm2-dump-db manpage if executable is installed

---

src/bin/util/softhsm2-util-ossl.cpp
src/bin/util/softhsm2-util-ossl.h

softhsm2-util had no support for importing ECDSA keys when building with OpenSSL

Added support for importing ECDSA keys with OpenSSL

---

src/lib/P11Objects.cpp

The PKCS spec requires processing to fill in all attributes in the array, if one of the benign error codes (SENSITIVE, TYPE_INVALID, BUFFER_TOO_SMALL) is returned.

Fix for bug in C_GetAttributeValue, which bails at the first error

---

src/bin/common/library.cpp
src/lib/data_mgr/SecureAllocator.h

I've been able to build both 32-bit and 64-bit release of SoftHSMv2 in Visual Studio 2015 Community with these simple changes.

Fix errors reported by Visual Studio 2015

---

src/lib/SoftHSM.cpp
src/lib/common/MutexFactory.cpp
src/lib/crypto/test/cryptotest.cpp
src/lib/data_mgr/SecureMemoryRegistry.cpp
src/lib/data_mgr/test/datamgrtest.cpp
src/lib/handle_mgr/test/HandleManagerTests.cpp
src/lib/handle_mgr/test/handlemgrtest.cpp
src/lib/object_store/test/ObjectStoreTests.cpp
src/lib/slot_mgr/test/SlotManagerTests.cpp
win32/convarch/convarch.vcxproj.in
win32/cryptotest/cryptotest.vcxproj.in
win32/datamgrtest/datamgrtest.vcxproj.in
win32/dump/dump.vcxproj.in
win32/handlemgrtest/handlemgrtest.vcxproj.in
win32/keyconv/keyconv.vcxproj.in
win32/objstoretest/objstoretest.vcxproj.in
win32/p11test/p11test.vcxproj.in
win32/sessionmgrtest/sessionmgrtest.vcxproj.in
win32/slotmgrtest/slotmgrtest.vcxproj.in
win32/softhsm2/softhsm2.vcxproj.in
win32/util/util.vcxproj.in

MutexFactory is destroyed before SecureMemoryRegistry but SecureMemoryRegistry needs MutexFactory so destruction of SecureMemoryRegistry make the mess !
I propose to invert instanciation sequence of  SecureMemoryRegistry and MutexFactory to allow the atexit function calling the destructors into the right order. 
The second commit is about warnings and compilations options under windows

softhsm2-util crash under WIndows

---

src/lib/data_mgr/SecureDataManager.cpp

When a PKCS#11 object is created, a default value is assigned to each of its attributes. Some of these attributes are then [updated](https://github.com/opendnssec/SoftHSMv2/blob/dd6337892b856432aa1dcf0abe00aa8fc1678e49/src/lib/P11Objects.cpp#L220) using values taken from a supplied template. If the object in question is private, the attribute update process involves [encrypting](https://github.com/opendnssec/SoftHSMv2/blob/99d128a13d7da0d21c6d0f16aaa348f73a15df08/src/lib/P11Attributes.cpp#L56-L60) its value. However, the default (empty) values of some non-mandatory attributes (namely [`CKA_EXPONENT_1`](https://github.com/opendnssec/SoftHSMv2/blob/99d128a13d7da0d21c6d0f16aaa348f73a15df08/src/lib/P11Attributes.cpp#L1831-L1840), [`CKA_EXPONENT_2`](https://github.com/opendnssec/SoftHSMv2/blob/ …

Do not attempt decryption of empty byte strings

---

NEWS
src/lib/P11Attributes.cpp

This will fix issue #162.
CKA_CERTIFICATE_CATEGORY, CKA_NAME_HASH_ALGORITHM, and CKA_JAVA_MIDP_SECURITY_DOMAIN have invalid checks (should not be != but ==). Also removing the checks because they are handled when ck8 is not set on these attributes.
While at it, removing other abundant checks. This is handled by the parent function.

Not possible to create certificate objects

---

src/bin/common/getpw.cpp

comparison between signed and unsigned integer expressions [-Wsign-compare]

Resolves compiler warning.

---

src/lib/crypto/OSSLCryptoFactory.cpp

A single instance of the OpenSSL libcrypto library can be shared by the main application and its libraries, including `libsofthsm2.so`.  To enable it, the libcrypto API checks if each individual subsystem is already initialized, and prevents double initialization.  Initializing the same subsystem by multiple components (the main application or its libraries) is thus safe.
On the other hand, discarding (cleaning up) the state of a libcrypto subsystem breaks all other components using it.  Consequently, only the main application may safely perform cleanup of the OpenSSL libcrypto library.
See https://wiki.openssl.org/index.php/Library_Initialization#libcrypto_Initialization for details.
For example, the existing code causes applications to crash on `ENGINE_cleanup()`, since `libsofthsm2.so` …

Stop discarding the global OpenSSL libcrypto state

---

src/lib/SoftHSM.cpp
src/lib/slot_mgr/SlotManager.cpp
src/lib/slot_mgr/SlotManager.h
src/lib/slot_mgr/test/SlotManagerTests.cpp
src/lib/slot_mgr/test/SlotManagerTests.h

Calling C_GetSlotList with NULL_PTR will now make sure that there is always a slot with an uninitialized token.

Add a slot with an uninitialized token by calling C_GetSlotList with NULL_PTR

---

src/bin/common/library.cpp

This patch fixes segmentation faults in loadLibrary function on Windows when PKCS#11 library is not found.

Fix segmentation faults in loadLibrary function

---

src/lib/test/AsymEncryptDecryptTests.cpp
src/lib/test/AsymWrapUnwrapTests.cpp
src/lib/test/DeriveTests.cpp
src/lib/test/DigestTests.cpp
src/lib/test/InfoTests.cpp
src/lib/test/InitTests.cpp
src/lib/test/InitTests.h
src/lib/test/ObjectTests.cpp
src/lib/test/README
src/lib/test/RandomTests.cpp
src/lib/test/SessionTests.cpp
src/lib/test/SignVerifyTests.cpp
src/lib/test/SymmetricAlgorithmTests.cpp
src/lib/test/TestsBase.cpp
src/lib/test/TestsNoPINInitBase.cpp
src/lib/test/TestsNoPINInitBase.h
src/lib/test/TokenTests.cpp
src/lib/test/UserTests.cpp
src/lib/test/p11test.cpp

I have modified the cppunit test so that it also can test other p11 implementations.
If the test is built as before (make p11test) you will get the same test that you had before (static linking of the SoftHSMv2 p11).
But with this change it will also be possible to build the test so that any p11 implementation with a shared library could be tested.
I have also added 2 new options to the test (no arguments will test as before):
- Printing of test name before a test is executed. This is good if the p11 that you are testing is crashes when some test is executed.
- Possibility to run a specific test. This is good to have when debugging
The new build and execution options are documented in: ./src/lib/test/README
I believe that it will be good for the SoftHSM project if the test is used for …

Possibility to test other p11 implementation with the cppunit test.

---

src/lib/SoftHSM.cpp
src/lib/test/SymmetricAlgorithmTests.cpp
src/lib/test/SymmetricAlgorithmTests.h

If "no padding" ciphering was done with C_EncryptUpdate or C_DecryptUpdate then the call failed when the updated part was not a multiple of the block size.
This is wrong; these functions must handle any part length.
The requirement of multiple block size does only affect C_EncryptFinal and C_DecryptFinal; when any of these functions is called then the total length must be a multiple of the block size.
This commit fixes these issues.
Also the prediction for the needed output buffer length that is returned when a crypto function is called with NULL_PTR as input should now be more accurate.
To do a thorough test of all this, the "p11test" has been enhanced to use different part lengths to the update function.

Fixing of no padding cipher. 

---

src/lib/crypto/OSSLCryptoFactory.cpp

We use CRYPTO_set_id_callback() to set a callback, but we don't ever
remove it again on unload. So OpenSSL crashes the next time it needs a
thread-id.
CRYPTO_set_id_callback() has been deprecated since OpenSSL 1.0.0, the
oldest we support. And redundant too, since OpenSSL has fallbacks which
include the address of errno. Which is going to work on any platform
with pthreads... and we were only calling CRYPTO_set_id_callback() on
platforms with pthreads.
So just rip it out.

Issue #239: Crash on module unload with OpenSSL

---

src/lib/common/SimpleConfigLoader.cpp

Values of all environment variables seems to be cached when Visual C++ redistributable libraries are loaded into the process. Any later call to `getenv()` function returns only cached values regardless of any subsequent environment modifications. More detailed analysis of this phenomenon has been previously published at [codeproject.com](http://www.codeproject.com/Articles/43029/When-what-you-set-is-not-what-you-get-SetEnvironme).
I have personally encountered this IMO strange behavior in [pkcs11-logger project](https://github.com/Pkcs11Interop/pkcs11-logger) and fixed it easily by reading the values of environment variables with `GetEnvironmentVariable()` function instead of `getenv()` function. Proposed patch does the same for `SOFTHSM2_CONF` environment variable.
I believe this patch …

Use GetEnvironmentVariable instead of getenv on Windows

---

appveyor.yml
appveyor_build.bat
appveyor_download_requirements.ps1
win32/util/util.vcxproj.in

This PR adds build scripts for [AppVeyor CI service for Windows](https://www.appveyor.com/). Prebuilt dependencies (OpenSSL and CppUnit) are currently hosted in dedicated repository [disig/SoftHSM2-AppVeyor](https://github.com/disig/SoftHSM2-AppVeyor). 
You can examine this build process performed on my fork at https://ci.appveyor.com/project/ci-asn1net/softhsmv2. Examples of build output can be found at https://ci.appveyor.com/project/ci-asn1net/softhsmv2/build/job/tuwg7jxxjuq5aytd/artifacts and https://ci.appveyor.com/project/ci-asn1net/softhsmv2/build/job/ybmrsqp8eyt89ycb/artifacts
If you want to merge this PR and set up the build process for your repository you will need to link github account with AppVeyor (can be dedicated accout for this task). We are ready to assist you and …

Add automated SoftHSM2 build with AppVeyor service.

---

Makefile.am
configure.ac
softhsm2.module.in
testing/build-softhsm2.sh

In order for well-behaved applications to discover and use the PKCS#11
provider module, we should install a p11-kit module file for it.

Issue #230: Install p11-kit module file

---

win32/Configure.py
win32/keyconv/keyconv.vcxproj.in

I've received following errors when building current `develop` branch on WIN10 with VS2015 and OpenSSL 1.1.0b:
```
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp__ioctlsocket@12 referenced in function _BIO_socket_ioctl
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp__getsockname@12 referenced in function _BIO_sock_info
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp__getsockopt@20 referenced in function _BIO_sock_error
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp__getsockopt@20
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp__ntohs@4 referenced in function _BIO_get_port
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol …
```

Add missing dependency on winsock

---

m4/ax_cxx_compile_stdcxx_11.m4

Strangely enough Mac 10.8 passes the other C++11 checks
but does not have std::unique_ptr.

Fix c++11 check to look for unique_ptr

---

src/bin/util/softhsm2-util-botan.cpp
src/bin/util/softhsm2-util-ossl.cpp

When importing keys with the `softhsm2-util` the private and public key objects were attributed so that they couldn't be used for de-/encryption. This pull-request sets the attributes
* `CKA_WRAP`/`CKA_ENCRYPT` for the public key, and
* `CKA_UNWRAP`/`CKA_DECRYPT` for the private key
to true. This is supposed to fix #257

Set CKA_DECRYPT/CKA_ENCRYPT flags on key import to true.

---

OSX-NOTES.md

Updated command line tools package name and to current as of 4-Jan-2016.
Made note of brew Caveat for libtool prepending a ‘g’.
Removed AM_INIT_AUTOMAKE update to configure.ac as this is already done.
By trial and error, I found that both softhsm2.conf AND
softhsm2-alt.conf must be edited as shown in order to avoid various
assertion errors generated by p11test in InfoTest.cpp.
There are still some compile-time warnings that may/may not be an
issue. Most concerning would appear to be:
DB.cpp:77:17: warning: 'va_start' has undefined behavior with reference
types [-Wvarargs]
va_start(args, format);
^
All tests performed by ‘check’, however, pass.

Editorial changes from Mountain Lion to Sierra.

---

src/lib/test/SymmetricAlgorithmTests.cpp

Macro needed for the shared library test forgotten. Added it back.

Fix test of p11 shared library.

---

m4/acx_openssl_gost.m4
src/lib/crypto/OSSLComp.cpp
src/lib/crypto/OSSLComp.h
src/lib/crypto/OSSLCryptoFactory.cpp
src/lib/crypto/OSSLDHPrivateKey.cpp
src/lib/crypto/OSSLDHPublicKey.cpp
src/lib/crypto/OSSLDSAPrivateKey.cpp
src/lib/crypto/OSSLDSAPublicKey.cpp
src/lib/crypto/OSSLECDH.cpp
src/lib/crypto/OSSLECDSA.cpp
src/lib/crypto/OSSLRSAPrivateKey.cpp
src/lib/crypto/OSSLRSAPublicKey.cpp
win32/Configure.py

Hi,
Support libressl with trivial changes, passes all tests.
BTW: Running programs during autoconf is highly discouraged as cross-compile will fail. Please consider to use only the pre-processor in order to detect algorithms and versions.
BTW2: If you run something while allowing to specify --with-xxx=prefix, you should also set LD_PRELOAD.
Thanks!

crypto: openssl: libressl support

---

src/lib/crypto/OSSLAES.cpp

EVP_CipherFinal_ex is called without shift for output pointer -- so that
the final padded block is written at the begining of the output buffer,
and not appended to the result of the previous EVP_CipherUpdate.
It works now as expected because "padding is handled by cipher mode separately ..."
and final padded block has zero length.

Minor fix of 'EVP_CipherFinal_ex' call

---

src/lib/main.cpp

On macOS (at least 10.12) the library symbols are not visible so the
library can't be used.
The definition of PKCS_API could be smarter.
I inspired myself from https://github.com/LudovicRousseau/PCSC/blob/master/src/misc.h#L47

Export PKCS#11 symbols from the library

---

src/lib/crypto/test/Makefile.am
src/lib/data_mgr/test/Makefile.am
src/lib/handle_mgr/test/Makefile.am
src/lib/object_store/test/Makefile.am
src/lib/session_mgr/test/Makefile.am
src/lib/slot_mgr/test/Makefile.am
src/lib/test/Makefile.am

@CPPUNIT_CFLAGS@ was not correctly used.
So the cppunit header files were not found if not installed in the
default folder.

Issue #297: Fix build with cppunit

---

NEWS
m4/acx_botan_rawpss.m4
m4/acx_crypto_backend.m4
src/lib/SoftHSM.cpp
src/lib/crypto/BotanRSA.cpp
src/lib/crypto/BotanRSA.h
src/lib/crypto/SymmetricAlgorithm.cpp
src/lib/crypto/test/RSATests.cpp
src/lib/test/SignVerifyTests.cpp
win32/Configure.py
win32/config.h.in

CKM_RSA_PKCS_PSS was added in #335, but only for OpenSSL. This also add support for Botan.

Support raw PSS with Botan

---

src/bin/dump/common.h
src/bin/dump/softhsm2-dump-db.cpp
src/bin/dump/softhsm2-dump-file.cpp
src/lib/P11Attributes.cpp
src/lib/P11Attributes.h
src/lib/P11Objects.cpp
src/lib/SoftHSM.cpp
src/lib/SoftHSM.h
src/lib/object_store/DBObject.cpp
src/lib/object_store/File.cpp
src/lib/object_store/File.h
src/lib/object_store/OSAttribute.cpp
src/lib/object_store/OSAttribute.h
src/lib/object_store/ObjectFile.cpp
src/lib/object_store/test/DBObjectTests.cpp
src/lib/object_store/test/DBObjectTests.h
src/lib/object_store/test/FileTests.cpp
src/lib/object_store/test/ObjectFileTests.cpp
src/lib/object_store/test/ObjectFileTests.h
src/lib/object_store/test/SessionObjectTests.cpp
src/lib/object_store/test/SessionObjectTests.h
src/lib/test/ObjectTests.cpp
src/lib/test/ObjectTests.h

Took a stab at closing out #140, since I'm looking for this support for a project I'm working on.  
There are a couple of corners that I cut, and welcome feedback about how I can improve:
* I didn't create a new table in sqlite to hold mechanisms; rather, overloaded the byte string table. It's not entirely clear to me why different object types need different tables. In any case, I'd be happy to do something different, but would need to understand what an appropriate migration path would look like for users who are using a released version.
* I did not add support for mechanism lists in wrap/unwrap templates.  That probably ought to be there for this feature to be considered complete.
I will openly confess that my C++ is pretty novice, so I'd suggest that you probably want to be quite …

Support for CKA_ALLOWED_MECHANISMS

---

win32/Configure.py

Hi, I've successfully [built SoftHSM 2.4.0 with Visual Studio 2017 Community](https://github.com/disig/SoftHSM2-for-Windows/blob/2.4.0/BUILDING.md) but I had to pass `with-toolset=v141` parameter to `Configure.py` script. This micropatch adds VS2017 detection to `Configure.py` script.

Add VS2017 detection to Configure.py

---

src/lib/object_store/test/DBTests.cpp

I don't know why this wasn't a problem on `x86_64` builds, but this test failed on `x86` alpinelinux.
See: https://github.com/tcely/aports/blob/a6fdb70c45eb7ce9eff1dff0993eeb93a012bfb6/testing/softhsm/fix-objstoretest.patch
http://build.alpinelinux.org/buildlogs/build-edge-x86/testing/softhsm/softhsm-2.4.0-r0.log

Update DBTests.cpp to fix x86 test failure

---

src/lib/SoftHSM.cpp

If a PKCS11 API caller provided own mutex handling callbacks,
we need to ensure they aren't used after C_Finalize is called
and SoftHSM instance is recycled.
Inability to do so may lead to a situation where callbacks might
be provided by a different dynamically loaded object which is removed
after C_Finalize() call. Thus, callback pointers become invalid and
calling them leads to crashes.
Fixes: https://github.com/opendnssec/SoftHSMv2/issues/408
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>

Reset mutex callbacks to the default version when finished

---

src/lib/SoftHSM.cpp
src/lib/SoftHSM.h
src/lib/test/SymmetricAlgorithmTests.cpp
src/lib/test/SymmetricAlgorithmTests.h

Add support for CKM_GENERIC_SECRET_KEY_GEN which is required for HMAC operations in PKCS11 2.4.0.
Resolves #375

Add CKM_GENERIC_SECRET_KEY_GEN Support

---

src/lib/SoftHSM.cpp

I encountered this issue while attempting to diagnose the root cause of #417. I followed the procedures described by @parasssh, but I made two changes
1. I used a PKCS11 URL for which there was no matching object
2. I used the newly added `-check` flag in `openssl pkey`
I was using the latest master branches of SoftHSMv2 and lbp11. For OpenSSL, I used v1.1.1.
I then ran the command, resulting in a segfault
```
#pkey -engine pkcs11 -inform engine -in 'token=slot_111111-id=%11%11'   -check
engine "pkcs11" set.
Format not recognized!
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
The legacy ENGINE_pkcs11 ID format is also still accepted for now
Format not recognized!
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
The …
```

Set fields to NULL to avoid double free

---

README.md

Faced [issue ](https://github.com/opendnssec/SoftHSMv2/issues/429) while building from the repository because `libtool-ltdl-devel` was not installed.
Updated readme to reflect that.

Updated prerequisite to build from repository

---

src/lib/crypto/BotanEDKeyPair.cpp
src/lib/crypto/BotanEDKeyPair.h
src/lib/crypto/BotanEDPrivateKey.h
src/lib/crypto/BotanEDPublicKey.h

Loading libsofthsm2.so (built on Ubuntu 14.04 with botan) failed with:
ERROR: Could not load the PKCS#11 library/module: src/lib/libsofthsm2.so: undefined symbol: _ZN17BotanEDPrivateKeyD1Ev
Fixes #435 (a regression in 2.5.0 due to commit 2751555).
___
(verified this patch on Ubuntu 14.04, the library can load again, softhsm2-util init and import works.)

Issue #435: Fix botan build without EDDSA

---

m4/acx_botan_ecc.m4
m4/acx_botan_eddsa.m4
m4/acx_botan_gost.m4
m4/acx_crypto_backend.m4
m4/acx_openssl_ecc.m4
m4/acx_openssl_eddsa.m4
m4/acx_openssl_gost.m4

Currently the crypto algorithm settings are either enabled or disabled, this
makes it difficult to support permutations openssl, libressl, botan versions,
as these differ in capabilities.
In most cases, the library should use the crypto library capabilities unless
explicitly required otherwise by the users.
This change handles tree state value for the --enable-<algo>:
* detect [default] - set to yes/no based on supported detection.
* yes - must be supported and used.
* no - should not be used.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

build: detect crypto algorithms by default

---

src/lib/object_store/DBToken.cpp

The parentheses in the logic expression were wrong, not clearing the flags which should be cleared when user PIN is set.
In SoftHSMv2, this has the only effect of clearing USER_PIN_COUNT_LOW when user PIN is changed/initialized, as the other flags are never set. In OSToken, these flags are manipulated correctly.

Fix user PIN flags manipulation in DBToken

---

src/lib/P11Attributes.cpp
src/lib/data_mgr/ByteString.cpp

Addresses #449.
When `value` has size 0, the invalid reference  `&byteString[0]` in `ByteString::const_byte_str` will cause an assertion when built with the flag `-Wp,-D_GLIBCXX_ASSERTIONS` (used by default in distros like Fedora)

Perform copy only if value has size > 0.

---

.gitignore
configure.ac
src/lib/SoftHSM.cpp
src/lib/SoftHSM.h
src/lib/common/Configuration.cpp
src/lib/common/softhsm2.conf.5.in
src/lib/common/softhsm2.conf.in
src/lib/test/CMakeLists.txt
src/lib/test/InfoTests.cpp
src/lib/test/InfoTests.h
src/lib/test/Makefile.am
src/lib/test/softhsm2-mech.conf.in
src/lib/test/softhsm2-mech.conf.win32
win32/p11test/p11test.vcxproj.in

This is helpful for testing applications using PKCS#11 devices,
which do not have to provide all the variety of the mechanisms
provided by SoftHSM and might need to implement some checks
and possible fallback when detecting the algorithm to be used in the
upper protocol layers.
This is an addition to the `CKA_ALLOWED_MECHANISMS` attribute,
which is unfortunately not very widely used. It should serve the same
purpose better, but most of the tokens and PKCS#11 modules do not
provide it.

Provide a new configuration option to allow enabling and disabling various mechanisms

---

src/lib/P11Attributes.cpp
src/lib/test/ObjectTests.cpp

While investigating how the `CKA_ALLOWED_MECHANISMS` work, I noticed that I was getting wrong results when I read the attribute from the object. Some investigation turned out that the data is written with offset one for some reason and that this for some reason worked with the one test case (which stores the `CKA_ALLOWED_MECHANISMS` inside of `CKA_WRAP_TEMPLATE` attribute, that is currently in SoftHSM.
The attached patch set fixes the issue for me and adds a test case that verifies this work as expected (fails without the patch attached).

Fix allowed mechanisms set directly to the objects

---

src/lib/object_store/DB.cpp

When many parallel accesses happen on a network-backed storage (like a
busy Ceph RBD), the DB can be busy for longer than 15 seconds, leading
to failed token accesses. Increase the timeout to 3 minutes (a factor of
12).

Increase sqlite busy timeout from 15 seconds to 3 minutes

---

src/lib/crypto/OSSLCryptoFactory.cpp

in OSSLCryptoFactory destructor resources created by ENGINE_load_rdrand are not freed

memory leak in OSSLCryptoFactory destructor

---

src/lib/SoftHSM.cpp
src/lib/common/Configuration.cpp
src/lib/common/softhsm2.conf.5.in
src/lib/common/softhsm2.conf.in
src/lib/test/softhsm2-mech.conf.in
src/lib/test/softhsm2-mech.conf.win32

My rationale is that the configuration parameter overrides whatever
mechanisms are reported by the token itself, which is reported by the
"slot" object in SoftHSM.

Rename configuration option to "slots.mechanisms".

---

src/lib/SoftHSM.cpp
src/lib/test/InfoTests.cpp
src/lib/test/InfoTests.h

C_WaitForSlotEvent is expected to be supplied as a pkcs11 function by
libraries and applications, such as nss. Since the slots are never
updated it's quite easy to implement.
Would you like me to create an issue and add an entry into NEWS?

Add support for C_WaitForSlotEvent

---

src/lib/crypto/Botan_ecb.cpp

Commit b909778 made this constructor protected.
This is a contribution from [Ribose Inc](https://www.ribose.com) (@riboseinc).

Remove direct use of Exception class to work with modern Botan.

---

src/lib/SoftHSM.cpp
src/lib/test/SymmetricAlgorithmTests.cpp

Add NULL_PTR checks for number of PKCS#11 functions that take CK_ATTRIBUTE_PTR as input arguments. Since NULL_PTR is allowed when `ulCount` is 0, the conditionals also check the `ulCount` (or similar) argument.

Check CK_ATTRIBUTE_PTR arguments for NULL_PTR

---

.gitignore
configure.ac
src/lib/SoftHSM.cpp
src/lib/SoftHSM.h
src/lib/common/Configuration.cpp
src/lib/common/softhsm2.conf.5.in
src/lib/common/softhsm2.conf.in
src/lib/test/CMakeLists.txt
src/lib/test/ForkTests.cpp
src/lib/test/ForkTests.h
src/lib/test/Makefile.am
src/lib/test/softhsm2-reset-on-fork.conf.in
src/lib/test/softhsm2-reset-on-fork.conf.win32
win32/p11test/p11test.vcxproj.in

Add the configuration option "library.reset_on_fork".  When set to "true", will
make SoftHSM to reset its state on fork.
---
Was  "Add a configuration option to emulate hardware device"
Previous description:
Add the configuration option "slots.hardware".  When set to "true", will
make SoftHSM to set the CKF_HW_SLOT flag in the structure returned by
C_GetSlotInfo().
The added configuration option is useful for testing applications which
requires hardware slots and/or change behaviour for hardware slots.
Also reset the SoftHSM instance when a fork is detected and the
CKF_HW_SLOT flag is set. This emulates a common behaviour for
hardware devices.

Add a configuration option to reset SoftHSM state on fork

---

src/lib/crypto/OSSLCryptoFactory.cpp

Previously, the rdrand_engine was not being freed in OSSLCryptoFactory
destructor.  With this change the rdrand_engine will be freed avoiding
memory leak.
Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

Fix memory leak in OSSLCryptoFactory

---

src/lib/SoftHSM.cpp
src/lib/SoftHSM.h

Memory leak while freeing up resources.  This leak will only become
evident when destroying SoftHSM, like in unloading the shared libary
of when using the close-on-fork.  Not even when performing C_Finalize
or closing the application as the C++ library will clean up the latter.

Memory leak upon clearing resources or unloading

---

src/lib/SoftHSM.cpp

This is a follow-up on #418 
I was investigating a crash similar to #417 which happened if a wrong PIN was provided when using the openssl + engine_pkcs11 + SoftHSM combination. The root of the problem is that the destructor for SoftHSM can be executed before the ``atexit()`` handlers installed by other libraries holding references to SoftHSM.
In one particular case, the engine_pkcs11 would call ``SoftHSM::C_CloseSession()`` when exiting, which would end in a crash in ``HandleManager::getSession()`` because the ``handleManager`` had been destroyed earlier.
The bug was reported as part of https://github.com/OpenSC/libp11/issues/273

Mark as not initialized in destructor

---

src/lib/object_store/SessionObjectStore.cpp

Moves the locking point when deleting objects forward to fix #518

Fix issue #518 by locking before the object set is accessed

---

src/lib/SoftHSM.cpp
src/lib/test/SymmetricAlgorithmTests.cpp

Add CK_KEY_TYPE checks at C_EncryptInit and C_DecryptInit just like in MacSignInit(). Fixes test cases on the way.

Check key type in C_EncryptInit and C_DecryptInit

---

src/lib/SoftHSM.cpp

I noticed weird behavior when the library is loaded into longer-running
process, which issues several cycles of C_Initialize & C_Finalize,
where I saw exactly the same amount of duplicate items as the amount
of the calls to C_Initialize.
I was not able to replicated it in a testsuite, probably because of
different way how the memory is handled inside of C++ code and when
called from C code as a PKCS#11 library.
This fix is just making sure that the list is empty before filling it
with new mechanisms. Other possiblity would be to move the clean to
C_Finalize(), which is counterpart to the C_Initialize(), containing
the initialization of this list.

Avoid creating duplicate mechanisms

---

src/lib/SoftHSM.cpp
src/lib/test/SymmetricAlgorithmTests.cpp
src/lib/test/SymmetricAlgorithmTests.h

This PR implements a fix for issue #469 and adds a test case to check if ```C_EncryptFinal``` and ```C_DecryptFinal``` correctly return ```CKR_ARGUMENTS_BAD``` when a ```NULL_PTR``` is provided in the return length field.

Implemented fix and testcase for missing NULL_PTR validation

---

src/lib/crypto/PrivateKey.h
src/lib/crypto/PublicKey.h

Allow compilation on macOS 10.15.4, Xcode 11.4

---

src/bin/util/softhsm2-util-ossl.cpp
src/lib/SoftHSM.cpp
src/lib/crypto/OSSLEDDSA.cpp
src/lib/crypto/OSSLEDPrivateKey.cpp
src/lib/crypto/OSSLEDPublicKey.cpp
src/lib/crypto/OSSLUtil.cpp
src/lib/crypto/test/EDDSATests.cpp
src/lib/crypto/test/EDDSATests.h
src/lib/test/DeriveTests.cpp
src/lib/test/DeriveTests.h
src/lib/test/SignVerifyTests.cpp
src/lib/test/SignVerifyTests.h

This puts the finishing touches on the OpenSSL Ed448/X448 implementation. I'm able to successfully run BIND's Ed448 DNSSEC tests with these changes.

Get OpenSSL Ed448/X448 working

---

src/lib/crypto/OSSLCryptoFactory.cpp

As of 1.1.0, OpenSSL registers its own atexit() handler to call
OPENSSL_cleanup(). If our own code subsequently tries to, for example,
unreference an ENGINE, then it'll crash or deadlock with a use after
free.
Fix it by registering a callback with OPENSSL_atexit() to be called when
OPENSSL_cleanup() is called. It sets a flag which prevents any further
touching of OpenSSL objects — which would otherwise happen fairly much
immediately thereafter when our own OSSLCryptoFactory destructor gets
called by the C++ runtime's own atexit() handler.
Fixes: #548

Issue #548: Don't clean up engines after OpenSSL has already shut down

---

src/lib/crypto/OSSLCryptoFactory.cpp

We can't register our own atexit() or OPENSSL_atexit() handler because
there's no way to unregister it when the SoftHSM DSO is unloaded. This
causes the crash reported at https://bugzilla.redhat.com/1831086#c8
Instead of using that method to set a flag showing that OPENSSL_cleanup()
has occurred, instead test directly by calling OPENSSL_init_crypto() for
something that *would* do nothing, but will fail if OPENSSL_cleanup()
has indeed been run already.
Fixes: c2cc0652b4 "Issue #548: Don't clean up engines after OpenSSL
has already shut down"

Fix OPENSSL_cleanup() detection without using our own atexit() handler

---

src/lib/crypto/BotanEDDSA.cpp
src/lib/crypto/OSSLEDDSA.cpp
src/lib/test/ForkTests.cpp

The section "2.3.10 Edwards Elliptic curve key pair generation" lists the key limits as following:
> For this mechanism, the only allowed values are 255 and 448 as RFC 8032 only defines curves of these two sizes.
> A Cryptoki implementation may support one or both of these curves and should set the ulMinKeySize and ulMaxKeySize fields accordingly.
[1] https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/csprd01/pkcs11-curr-v3.0-csprd01.html#_Toc10560876

Fix advertised min and max mechanism sizes according to final PKCS#11 3.0 specification

---

src/lib/object_store/ObjectFile.cpp

Fix race condition between C_FindObjects and object creation (issue 573)

---

src/lib/SoftHSM.cpp
src/lib/test/DeriveTests.cpp
src/lib/test/DeriveTests.h

Added derive support with CKM_CONCATENATE_DATA_AND_BASE, CKM_CONCATENATE_BASE_AND_DATA and CKM_CONCATENATE_BASE_AND_KEY.

Add misc derivations

---

src/lib/SoftHSM.cpp

This generates unnecessary error messages when using multiple SoftHSM devices (different slots) with OpenDNSSEC.

Reduce the level of the log message when SoftHSM is already initialized

---

src/lib/common/softhsm2.conf.5.in

this is broken since the rename in 03c6202a

doc: Fix category title to reflect the actual option name

---

src/lib/object_store/File.cpp

Destroying the File object will call fclose() and this will flush writes but this should only happen while the file is still locked.
Flush pending writes before every unlock. This also discards all unused data fetched from the file while locked, because it is now stale.
SoftHSM is writing to token.object files after unlocking, when the File is destroyed:
```
20:54:22.344661 openat(AT_FDCWD, "/var/lib/softhsm/tokens//4184d325-ecda-4355-83b1-6f4156b0fde0/token.object", O_RDWR|O_CREAT, 0640) = 5
20:54:22.344686 fcntl(5, F_GETFL)       = 0x8002 (flags O_RDWR|O_LARGEFILE)
20:54:22.344703 fcntl(5, F_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
20:54:22.344722 openat(AT_FDCWD, "/var/lib/softhsm/tokens//4184d325-ecda-4355-83b1-6f4156b0fde0/token.lock", …
```

Flush files before unlocking

---

src/lib/test/InfoTests.cpp

another shared library than SoftHSM.

InfoTests::testGetMechanismNegativeListConfig() not working when testing

---

CMakeLists.txt
config.h.in.cmake

The config option DEFAULT_UMASK was introduced with commit de5bb8a but
hasn't been added to CMake configuration.

Fix CMake build by adding DEFAULT_UMASK

---

m4/acx_crypto_backend.m4

compilation with Botan crypto backend on Ubuntu 18 fails.
way to reproduce:
```
$ sudo apt install libbotan-2-dev
$ sudo apt list --installed | grep botan
libbotan-2-dev/bionic,now 2.4.0-5ubuntu1 amd64 [installed]
$ ./autogen.sh
$ ./configure --with-crypto-backend=botan 
$ make
....lot of output....
BotanUtil.cpp:172:13: error: ‘class Botan::BER_Object’ has no member named ‘is_a’
if (object.is_a(Botan::PRINTABLE_STRING, Botan::ASN1_Tag(0)))
^~~~
```
BER_Object is defined in include/botan-2/botan/asn1_obj.h
Member function 'is_a' was added in [Botan version 2.5](https://github.com/randombit/botan/blob/2.5.0/src/lib/asn1/asn1_obj.h)

fix check minimal Botan version

---

src/bin/util/softhsm2-util.1
src/bin/util/softhsm2-util.cpp

Enables access to build configuration.
Currently implemented the `default-pkcs11-lib` variable to print the default
PKCS#11 library path.
Useful for applications which are using the softhsm2-util and require to
find the provider in filesystem which is used by the utility as there is no
standard process to locate the library.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

softhsm2-util: add --show-config parameter

---

src/lib/P11Objects.cpp

Since the transaction is not aborted in the db backend after an incorrect object creation request is made, the database access process fails in the next database access calls.
> ondergormez@ondergormez-IdeaPad:$ ./CreateTokenObject10times.py 
exception1: CKR_TEMPLATE_INCOMPLETE (0x000000D0)
exception2: CKR_GENERAL_ERROR (0x00000005)
exception3: CKR_GENERAL_ERROR (0x00000005)
exception4: CKR_GENERAL_ERROR (0x00000005)
exception5: CKR_GENERAL_ERROR (0x00000005)
exception6: CKR_GENERAL_ERROR (0x00000005)
exception7: CKR_GENERAL_ERROR (0x00000005)
exception8: CKR_GENERAL_ERROR (0x00000005)
exception9: CKR_GENERAL_ERROR (0x00000005)
exception10: CKR_GENERAL_ERROR (0x00000005)
ondergormez@ondergormez-IdeaPad:$
The syslog output of the above operations;  
> ondergormez@ondergormez-IdeaPad:$ less …

Fix "Transaction in database is already active." bug

---

src/lib/SoftHSM.cpp
src/lib/test/SymmetricAlgorithmTests.cpp
src/lib/test/SymmetricAlgorithmTests.h

Fixes issue #585 by properly resetting encrypt or decrypt operation status when one of the input parameter validation checks fails with `CKR_ARGUMENTS_BAD`.

Fix issue 585 by resetting en/decrypt op on input validation

---

src/lib/SoftHSM.cpp

When using C_UnwrapKey with CKM_xxx_CBC_PAD, the unwrapping key and
cipher objects were not being recycled on success.

Fix memory leak in SoftHSM::UnwrapKeySym.

---

.github/workflows/ci.yml
src/lib/test/CMakeLists.txt

Since Travis CI is no longer free as before, and there are issues with AppVeyor we currently don't have a working CI.
This PR adds a basic CI run which build and run tests for both crypto backends on Linux, Mac and Windows.
An example run: https://github.com/Nordix/SoftHSMv2/actions/runs/7718456304
The failed botan run is related to #724
Windows vcpkg's are cached for faster builds, but there are a lot of other improvements that could be done to this CI.
Examples are running sanitizers/valgrind/Coverity on Linux or using later OpenSSL version.
In general we would like to support this project, and adding a CI which can indicate existing issues is a start.
WDYT @halderen @rijswijk @jschlyter ?

Add GitHub Actions CI

---

CMakeLists.txt

macOS uses .dylib and this is the only thing that prevents using CMake on macOS.

fix: Use CMAKE_SHARED_LIBRARY_SUFFIX instead of hardcode .so

---

.github/workflows/ci.yml
src/lib/crypto/BotanSymmetricAlgorithm.cpp
src/lib/crypto/Botan_ecb.h
src/lib/crypto/CMakeLists.txt
src/lib/test/SymmetricAlgorithmTests.cpp

This PR includes the following commits to be able to run all tests on the different platforms in CI.
* Revert removal of Botan 2.0 ECB handling 
The ECB handling was added when Botan 2.0 was introduced via:
https://github.com/softhsm/SoftHSMv2/pull/294
but then removed by comments in (and later removed completely):
https://github.com/softhsm/SoftHSMv2/pull/717 via: https://github.com/softhsm/SoftHSMv2/commit/8fd89ec33edfe4a7b510c471101f78b52a0c1294
This commit reverts parts of this commit to get a stable state.
We could remove it fully in a separate PR, but then we should also remove the files Botan_ecb.h and Botan_ecb.cpp,
and avoid running some tests on Botan.
* Correcting build options for Windows in CI 
The CI installed libraries `Botan` and `OpenSSL` (x86 only) lacks support for …

Fix Botan build and test failures

---

src/bin/util/softhsm2-util-botan.cpp
src/bin/util/softhsm2-util-ossl.cpp

Fix for issue #746.
Also removes the need for NULL termination since we are dealing with binary data.

Fixes AES secret key import failing on newline characters

---

src/lib/object_store/Generation.cpp
src/lib/object_store/Generation.h
src/lib/object_store/OSToken.cpp
src/lib/object_store/ObjectFile.cpp

The "true" in the call to Generation::create() in OSToken::OSToken() is
used as the umask when it's supposed to be the isToken value (#566).
Remove the default value from isToken because it's dangerous and there are
only two callers. Explicitly pass "true" and "false" for isToken.
Failing to consider this a token generation file means that the value is
never refreshed for read-only operations. All objects are reloaded from
disk every time one of them is refreshed. List operations take a long time
because all of the objects are re-read for each object.
Fixes #680.

Fix severe peformance issue accessing keys

---

src/bin/util/softhsm2-util-botan.cpp
src/bin/util/softhsm2-util-ossl.cpp
src/bin/util/softhsm2-util.1
src/bin/util/softhsm2-util.cpp
src/bin/util/softhsm2-util.h

The softhsm2-util already support importing keys, why not also import
certificates?
Useful for test scripts that require both keys and certificates.
Add --import-type <type> parameter, depreciate the --aes parameter.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

Support import certificate using softhsm2-util
