softhsm/SoftHSMv2

NEWS, src/lib/SoftHSM.cpp, src/lib/SoftHSM.h, src/lib/common/Configuration.cpp, src/lib/common/Configuration.h, src/lib/common/MutexFactory.cpp, src/lib/common/MutexFactory.h, src/lib/common/SimpleConfigLoader.cpp, src/lib/common/SimpleConfigLoader.h, src/lib/crypto/BotanCryptoFactory.cpp, src/lib/crypto/BotanCryptoFactory.h, src/lib/crypto/OSSLCryptoFactory.cpp, src/lib/crypto/OSSLCryptoFactory.h, src/lib/data_mgr/SecureMemoryRegistry.cpp, src/lib/data_mgr/SecureMemoryRegistry.h, src/lib/object_store/SessionObjectStore.cpp, src/lib/object_store/SessionObjectStore.h, src/lib/object_store/test/SessionObjectStoreTests.cpp
Jakob, please check and merge this pull request.
=> SUPPORT-155: auto_ptr is deprecated

NEWS, src/lib/P11Attributes.cpp, src/lib/SoftHSM.cpp, src/lib/SoftHSM.h, src/lib/cryptoki_compat/pkcs11.h, src/lib/test/DeriveTests.cpp, src/lib/test/DeriveTests.h
Using DH, ECDH or symmetric encryption.
Jakob, please review and merge.
=> SUPPORT-139: Support deriving generic secrets, DES, DES2, DES3, and AES.

NEWS, src/bin/util/softhsm2-util-botan.cpp, src/bin/util/softhsm2-util-botan.h
Jakob, please check and merge this
=> SOFTHSM-119: softhsm2-util: Support ECDSA key import

NEWS, src/lib/crypto/OSSLGOSTPrivateKey.cpp
=> SOFTHSM-120: Segfault after renaming variables

src/lib/SoftHSM.cpp
* Symmetric encryption functions using multi-part behavior are implemented in
SoftHSMv2. However, the corresponding operations for decryption are not
available. This patch adds the symmetric code for decryption.
=> Add C_DecryptUpdate/C_DecryptFinal for sym ops.

NEWS, src/lib/test/SymmetricAlgorithmTests.cpp
Jakob, please check and merge this after #121
=> SOFTHSM-121: Test cases for C_DecryptUpdate/C_DecryptFinal

NEWS, configure.ac, m4/acx_destructor.m4, src/lib/SoftHSM.cpp
=> SOFTHSM-123: Fix library cleanup on BSD

README.md
Added note about the GNU Autotools build dependency and command for generating the configure script
=> Updated installation instruction in README

configure.ac, src/lib/SoftHSM.cpp, src/lib/SoftHSM.h, src/lib/common/Configuration.cpp, src/lib/common/softhsm2.conf.5.in, src/lib/test/InfoTests.cpp, src/lib/test/InfoTests.h, src/lib/test/softhsm2-alt.conf.in
Please consider this as a fix for #166.
=> add slots.removable config option

NEWS, src/lib/SoftHSM.cpp, src/lib/SoftHSM.h
#156 was closed, but it contained good changes.
=> Issues found by PVS-Studio

win32/Configure.py, win32/convarch/convarch.vcxproj.in, win32/cryptotest/cryptotest.vcxproj.in, win32/datamgrtest/datamgrtest.vcxproj.in, win32/dump/dump.vcxproj.in, win32/handlemgrtest/handlemgrtest.vcxproj.in, win32/keyconv/keyconv.vcxproj.in, win32/objstoretest/objstoretest.vcxproj.in, win32/p11test/p11test.vcxproj.in, win32/sessionmgrtest/sessionmgrtest.vcxproj.in, win32/slotmgrtest/slotmgrtest.vcxproj.in, win32/softhsm2/softhsm2.vcxproj.in, win32/util/util.vcxproj.in
* autodetect PlatformToolset version from visual studio install folder name
* check if script is launch from a vs command prompt
* add with-toolset param to configure script to overwrite platformtoolset auto detection
* add PLATFORMTOOLSET tokens to the visual studio project files templates
=> configure script improvements

NEWS, src/lib/object_store/DBObject.cpp, src/lib/object_store/DBObject.h, src/lib/object_store/DBToken.cpp, src/lib/object_store/DBToken.h, src/lib/object_store/OSObject.h, src/lib/object_store/OSToken.cpp, src/lib/object_store/OSToken.h, src/lib/object_store/ObjectFile.cpp, src/lib/object_store/ObjectFile.h, src/lib/object_store/ObjectStore.h, src/lib/object_store/ObjectStoreToken.h, src/lib/object_store/SessionObject.cpp, src/lib/object_store/SessionObject.h, src/lib/object_store/test/DBTokenTests.cpp, src/lib/object_store/test/OSTokenTests.cpp, src/lib/slot_mgr/Token.cpp, src/lib/test/TokenTests.cpp
But all token objects are deleted, the user PIN is removed and the token label is updated.
=> Issue #186: Reinitializing a token will now keep the token

OSX-NOTES.md
Had to do this on El Capitan 10.11.6
=> add the libtool install command for OSX

NEWS, OSX-NOTES.md
Needed to adjust the install notes when testing #215
=> Issue #215: Update the Homebrew install notes for OSX.

win32/util/util.vcxproj.in
Added missing library reference in util project which prevented successful building on windows. This issue was mentioned also in #237.
=> added EXTRALIBS to utils project

.travis.yml, Makefile.am, NEWS, README.md, configure.ac, m4/acx_p11kit.m4, softhsm2.module.in, testing/build-softhsm2.sh
=> Issue #230: Move configuration to an M4 script and update documentation

.appveyor.yml, testing/appveyor/appveyor_build.bat, testing/appveyor/appveyor_download_requirements.ps1
This PR enhances build scripts for [AppVeyor CI service for Windows](https://www.appveyor.com/). 
I have added support for openssl-1.1.0b and support for botan-1.10.13 (openssl-1.0.2g is already supported).
=> Enhanced appveyor build

.gitignore, src/lib/crypto/test/cryptotest.cpp, src/lib/data_mgr/test/datamgrtest.cpp, src/lib/handle_mgr/test/handlemgrtest.cpp, src/lib/object_store/test/objstoretest.cpp, src/lib/session_mgr/test/sessionmgrtest.cpp, src/lib/slot_mgr/test/slotmgrtest.cpp, src/lib/test/p11test.cpp, testing/build-botan.sh, testing/build-softhsm2.sh, testing/lib.sh
- more temporary files that are not git ignored
- ROOT is a directory used on the new jenkins environment
- Add support for building on Slackware Linux distribution
- Botan version no longer available at that URL in building script
- let cpp unit tests output for XML file to be picked up be Jenkins
environment.
=> Change to enable builds and reports on new Jenkinks environment

NEWS, src/lib/SoftHSM.cpp, src/lib/object_store/Generation.cpp, src/lib/object_store/OSToken.cpp, src/lib/object_store/ObjectFile.cpp
Remember to unlock files when returning upon an error and do not add an invalid object to the token.
=> Issue #358: Race condition when using two applications

src/lib/object_store/test/DBTests.cpp
Reverts opendnssec/SoftHSMv2#388, should go into develop and not master
=> Revert "Update DBTests.cpp to fix x86 test failure"

src/lib/P11Attributes.h
Contributing a fix for issue #393.   https://github.com/opendnssec/SoftHSMv2/issues/393
=> Fixing PublicKeyInfo Attribute type

src/lib/crypto/OSSLCryptoFactory.cpp
libressl and probably older openssl do not support this.
=> crypto: use ENGINE_load_rdrand with recent openssl

autogen.sh
More extensive regeneration autoconfiguration files.
=> autogen failure on undefined macro AC_MSG_ERROR

src/lib/handle_mgr/HandleManager.cpp, src/lib/handle_mgr/HandleManager.h
Possible solution to my reported issue 464
=> Do not release handlesMutex when no more open session exist on the slot (Issue #464)

src/lib/SoftHSM.cpp, src/lib/crypto/AsymmetricKeyPair.h, src/lib/crypto/AsymmetricParameters.h, src/lib/crypto/PrivateKey.h, src/lib/crypto/PublicKey.h, src/lib/crypto/SymmetricKey.cpp, src/lib/crypto/SymmetricKey.h, src/lib/object_store/DB.cpp, src/lib/object_store/UUID.h
=> Resolve issue #538

src/lib/test/ForkTests.cpp, src/lib/test/ForkTests.h, src/lib/test/InfoTests.cpp, src/lib/test/InfoTests.h, src/lib/test/InitTests.cpp, src/lib/test/README, src/lib/test/TestsNoPINInitBase.cpp, src/lib/test/TestsNoPINInitBase.h, src/lib/test/p11test.cpp
The unit tests is a very good tool to test other implementations.
These commits will change some tests so that testing of other implementations will have fewer failures.
=> Fixing tests of other PKCS#11 implementations.

src/lib/SoftHSM.cpp, src/lib/SoftHSM.h, src/lib/test/SymmetricAlgorithmTests.cpp, src/lib/test/SymmetricAlgorithmTests.h
This PR is to support wrapping and unwrapping of Edwards curve-based private keys.  Kindly consider and merge. Let me know if anything is missing.
=> implement wrapping and unwrapping of Edwards curve-based private keys

.github/workflows/ci.yml
PR to address minor changes to Github actions
=> Update Github actions
